### PR TITLE
Fix/commands fix #450, fix #546

### LINKED ISSUE #450: command: serviceDevCmd.runE() should return with an error
* when there is an error received from _eventsErrC_ or _resultsErrC_ execution should terminate.
* also we can directly return from loop when a signal received from chan _abort_

version [dev](https://github.com/mesg-foundation/core/commit/67b37ad2fa8ce8371544c14a08c55bdd42c64ebd)

### LINKED ISSUE #546: UI issue with service execute command
The loader is displayed weirdly when using `service execute` command without passing task and data

screen shot 2018-10-22 at 11 46 42

### PR DESCRIPTION
**Pull request by krhubert**
fix for #450 and #546

### CODE REVIEW

**Comment by krhubert** [comment]
@antho1404 can you fix the codeclimate issue?

**Comment by krhubert** [comment]
Also if you can force merge it it would be great, because tests are failing, but they are from container/daemon pkgs and they won't be solved in this PR

**Comment by krhubert** [comment]
Done

**Comment by krhubert** [comment]
close #516

**Comment by krhubert** [comment]
close #525

**Comment by krhubert** [comment]
close #519

**Comment by krhubert** [comment]
close #500

**Comment by antho1404** [comment]
yes please create different PR for that -> https://forum.mesg.com/t/keep-pull-requests-small/33

**Pull request closed without merging**
