### PR TITLE
Fix issue when many containers are created but only one is deleted

### PR DESCRIPTION
**Pull request by antho1404**
If a MESG service is created but has some errors like for example like that:

- A service that is connecting to a database
- a dependency that is running the database (influxdb for example)

When the MESG service starts with these two docker services, the first service will crash because it cannot access the database that takes time to start and will restart.

When it restarts docker stop the initial container but without destroying it so we needed to delete this container. If the initial service crashes multiple times, multiples containers are stopped but not deleted. This PR is fixing that by ensuring that all the remaining containers are actually deleted and doesn't block the execution of a new service and doesn't stuck the action to stop the MESG service (pending indefinitely because a container is still existing)

### CODE REVIEW

**Comment by ilgooz** [comment]
Tests are not passing.

**Comment by NicolasMahe** [comment]
> Tests are not passing.

@ilgooz When the test are failing with the following type of error, you can go on circleci and press rerun workflow. thx
```
panic: starting container failed: No such network: core [recovered]
	panic: starting container failed: No such network: core
```

**Comment by krhubert** [comment]
But the tests are not passing due to this error:

```
=== RUN   TestStopService
coverage: 87.3% of statements
panic: test timed out after 5m0s

goroutine 506 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1240 +0xfc
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44
```

It's timeout on test stop

**Comment by NicolasMahe** [comment]
Where do you see this test failing?
On circle ci, I see:
```
--- FAIL: TestIsRunning (0.61s)
panic: starting container failed: No such network: core [recovered]
	panic: starting container failed: No such network: core

goroutine 68 [running]:
testing.tRunner.func1(0xc42060c000)
	/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x7f0d20, 0xc4203b9010)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/mesg-foundation/core/daemon.startForTest()
	/go/src/github.com/mesg-foundation/core/daemon/start_test.go:31 +0x21c
github.com/mesg-foundation/core/daemon.TestIsRunning(0xc42060c000)
	/go/src/github.com/mesg-foundation/core/daemon/status_test.go:51 +0x26
testing.tRunner(0xc42060c000, 0x895ee8)
	/usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x2e0
FAIL	github.com/mesg-foundation/core/daemon	3.552s
```

**Comment by ilgooz** [comment]
> @ilgooz could you take a look and fix the test please?
> 
> Maybe we could do the test using docker mock? #588

@NicolasMahe Of course, by the way, let's merge testify mocks:  https://github.com/mesg-foundation/core/pull/588

**Pull request merged**
