### PR TITLE
Add marketplace service

### PR DESCRIPTION
**Pull request by NicolasMahe**

### CODE REVIEW

**Comment by antho1404** [comment]
- The `publishServiceVersion` works fine, just some feedback on the API https://github.com/mesg-foundation/marketplace/issues/15
- `sendSignedTransaction` works great
- The `listServices` task doesn't return anything
- I got an error with the `getService` (maybe timeout: 10000 is too low, why even a specific timeout)
```
service |  error while downloading manifest  ipfs :: QmcVUzKw1YHwpHi7V3hEcigq4PXhw26wuEK2TDL6pC7NBP RequestError: Error: ESOCKETTIMEDOUT
```
Didn't test the other tasks but I think some are not necessary:
- disableServiceOffer
- transferServiceOwnership

Also some could be done directly on marketplace.mesg.com:
- createServiceOffer
- purchase
This doesn't needs to be on the system service and can be done directly on the website with metamask and nice UI

**Comment by NicolasMahe** [comment]
Task `disableServiceOffer` and `transferServiceOwnership` removed

**Comment by NicolasMahe** [comment]
Task listServices fixed

**Comment by NicolasMahe** [comment]
closing in favor of #810

**Pull request closed without merging**
