### PR TITLE
Start service dependencies one by one

### PR DESCRIPTION
**Pull request by krhubert**
closes https://github.com/mesg-foundation/core/issues/382

### CODE REVIEW

**Comment by NicolasMahe** [comment]
What is the order of start?
Does the service start before the dependencies or the other way?

I would say it makes sense to start the dependencies first. (as the name suggest, the service is dependent on them).

**Comment by krhubert** [comment]
Before there was no order of starting. And it's the pbm because some dependencies may eg. connect to service and the other way and the other way, so it's hard to tell the one perfect order.

For example you deploy website as servcie and has db as a dependency so service must start first.

Second, you deploy database and eg. crawlers as a dependency in that case db must start first so crawler can connect to it

**Comment by NicolasMahe** [comment]
For info, the dependencies are started before the service itself. LGFM

**Comment by antho1404** [comment]
Why the dependencies are starting before the service ? This is just based on a map so it shouldn't by default, this needs to be added for me, I don't see how it can be done with the code here

**Comment by NicolasMahe** [comment]
Because of the way we transform the yaml to the go struct. See end of func deploy:
https://github.com/mesg-foundation/core/blob/fcea30b78145f1b27a3979555418560745a8186f/service/service.go#L193-L207

**Pull request merged**
