### PR TITLE
New documentation in the core

### LINKED ISSUE #253: Merge documentation to this repository
## Problem

Right now if we add a new feature we need once merged to update the documentation and this can leads to some mistakes or just some times the merge of the new feature can be done but the documentation not updated

## Solution

We could have the full documentation in the `docs` folder that already includes the cli doc and like that for every new feature we can directly update the documentation on the pull request and just update the documentation automatically when the pull request is merge.

Gitbook can be configured to point to a specific folder https://docs.gitbook.com/integrations/github#content-configuration

### PR DESCRIPTION
**Pull request by antho1404**
fixes #253

### CODE REVIEW

**Comment by NicolasMahe** [comment]
Modifs:
- [ ] Top menu links:
  - [ ] rename "Join" by "Discord"
  - [ ] rename "Contribute" by "GitHub"
  - [ ] change "Contribute" link to "github.com/mesg-foundation".
- [ ] The menu on the page CLI is weird. Can you put the content of the group core in the root?

**Comment by antho1404** [comment]
Can you review the new documentation 
https://deploy-preview-308--mesg-docs.netlify.com/

There is some new content, on the initial page and on the [api pages](https://deploy-preview-308--mesg-docs.netlify.com/api/core.html)

**Comment by NicolasMahe** [comment]
- [ ] add tutorial homepage to left menu

**Comment by antho1404** [comment]
What do you prefer between the light and dark version (dark to match the website if people come from the website which is about a third of users)

light: https://5b60058afdd72a65b66aa037--mesg-docs.netlify.com/
vs
dark: https://5b60058afdd72a65b66aa037--mesg-docs.netlify.com/

**Comment by NicolasMahe** [comment]
- [ ] feedback from Janie on Discord:
"Seamlessly connect any technologies to your application, from traditional web to new blockchain technologies"
"Any technologies can seamlessly be connected to your applications, from traditional web to new blockchain technologies"
If you're doing Event Driven in capitals - to remain consistent Technology Agnostic (A capitalized)
Scallable = scalable
Trully = truly
microservices one word
The only thing left to do is to connect theses services through their events.
"The only thing you have to do is connect services through their events". 
"All you have to do is connect services through their events."

**Comment by antho1404** [comment]
examples are part of the description so we can either put the table and bellow the description with example or the other way around but we cannot put the table in between (without having our own fork of this gen doc library)

**Comment by NicolasMahe** [comment]
- [ ] should add a "homepage" for API that says that the API is gRPC, and etc...

**Pull request merged**
