### PR TITLE
Create install curl script

### LINKED ISSUE #107: Create install curl script

### PR DESCRIPTION
**Pull request by NicolasMahe**
Close #107

### CODE REVIEW

**Comment by NicolasMahe** [comment]
@antho1404 how do we publish the file on https://get.mesg.tech ?

**Comment by antho1404** [comment]
just after installing it we cannot run the `mesg-core` command, If we open a new terminal it's fine I think we need to find a way to add the `source` in the end with the right file to source and reset the terminal

**Comment by antho1404** [comment]
I think we can just make a redirection from the subdomain `get` directly to the location of the file on github
Something like `get CNAME github.com/mesg-foundation/core/.../install.sh`

**Comment by NicolasMahe** [comment]
Put the install command in the doc and remove the `install.sh` file

**Comment by NicolasMahe** [comment]
I update the documentation with the install for mac.

**Pull request closed without merging**
