### PR TITLE
api: simplify file structure

### LINKED ISSUE #442: Combine feature files into one
In the `api` package we have all the time the same files `feature` and `feature_featurer` we should merge them together to keep the code simple

example:
`deploy_deployer.go`
`deploy.go`

### PR DESCRIPTION
**Pull request by ilgooz**
closes #442

### CODE REVIEW

**Comment by ilgooz** [comment]
@antho1404 I saw a test broken on CI, for this PR because of the small of buf size of dockertest chans. It was actually a fix.

**Comment by ilgooz** [comment]
good to review

**Comment by NicolasMahe** [comment]
@ilgooz can you fix the conflict please?

**Comment by ilgooz** [comment]
good to review

**Pull request merged**
