### PR TITLE
build for the cli

### PR DESCRIPTION
**Pull request by antho1404**

### CODE REVIEW

**Comment by antho1404** [comment]
@NicolasMahe I might need some help a bit on this one, the build is fine on local but fails on the ci...

**Comment by NicolasMahe** [comment]
Ok I'm checking it

**Comment by NicolasMahe** [comment]
could be usefull to upload release to github: https://github.com/tcnksm/ghr

**Comment by NicolasMahe** [comment]
another multi system build: https://github.com/mitchellh/gox

**Comment by NicolasMahe** [comment]
Fixed with model: https://github.com/ncw/rclone/blob/master/.circleci/config.yml

**Pull request merged**
