### PR TITLE
refactor service deploy statuses flags, closes #487

### LINKED ISSUE #487: rm aurora in deploy status messages of api & service packages
we can introduce a new flag something like _DONE_RED_ to distinct positive done messages from negative ones.

### PR DESCRIPTION
**Pull request by ilgooz**

### CODE REVIEW

**Comment by ilgooz** [comment]
@mesg-foundation/core please check the codeclimate errors. If we want to switch to _CamelCase_ then we need to it for all constants in the code base.

**Comment by antho1404** [comment]
please just change it for your PR, we will update the others when we have the warning touching these files or in a separated PR

**Comment by ilgooz** [comment]
good to review

**Comment by NicolasMahe** [comment]
@ilgooz don't forget to remove the branch once merged ;)

**Pull request merged**
